version: 0.0
os: linux
files:
  - source: /
    destination: /new_chatapp

hooks:
  BeforeInstall:
    - location: Dependency_Scripts/rmBeforeInstall.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: Dependency_Scripts/installDependency.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: Dependency_Scripts/startApplication.sh
      timeout: 60
      runas: root
